### ISSUE TITLE
install Error

### ISSUE THREAD

**Issue by alimoradynezhad** [pooya-mohammadi/deep_utils#44]
This installation command in Windows is accompanied by an error

 pip install git+https://github.com/pooya-mohammadi/deep_utils.git
 
   ERROR: Command errored out with exit status 1:
ppData\\Local\\Temp\\pip-req-build-r1tldw6i\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('
"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\moradi\AppData\Local\Temp\pip-pip-egg-info-i6z1fedb'
         cwd: C:\Users\moradi\AppData\Local\Temp\pip-req-build-r1tldw6i\
    Complete output (5 lines):
    ----------------------------------------
WARNING: Discarding git+https://github.com/pooya-mohammadi/deep_utils.git. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by pooya-mohammadi** [comment]
@alimoradynezhad 
Thanks for the feedback. The problem you mentioned is solved in commit [91771d1](https://github.com/pooya-mohammadi/deep_utils/commit/91771d193626b59fd003793c9e90b651e4fa0c56)
